direction: right

title: |md

  # SBOM Producer Life Cycle

| {near: top-center}

Authoring: {
  Generation
  Augmentation
  Enrichment
  Validation
  Signing
  Document Linking
}

Transportation

Analysis

Authoring.Generation -> Authoring.Augmentation
Authoring.Augmentation -> Authoring.Enrichment
Authoring.Enrichment -> Authoring.Validation
Authoring.Validation -> Authoring.Signing
Authoring.Signing -> Authoring."Document Linking"
Authoring."Document Linking" -> Transportation -> Analysis
